version: "3.9"

services:
  api:
    build: ./api
    environment:
      - CONNECTION_STRING=postgres://demo_user:demo_user@db/demo_db
    depends_on:
      - db
    networks:
      - network-api
      - network-web

  web:
    build: ./web
    environment:
      - API_URL=http://api:3001/data
    depends_on:
      - api
    ports:
      - "80:3000"
    networks:
      - network-web

  db:
    image: postgres:11.2-alpine
    ports: ["5432"]
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_user
      POSTGRES_DB: demo_db
    volumes:
      - ./sql_scripts/:/docker-entrypoint-initdb.d
    networks:
      - network-api

networks:
  network-api:
  network-web:
